"""empty message

Revision ID: 5125b8576862
Revises: 40f58b15ecd0
Create Date: 2022-02-08 12:59:58.773328

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5125b8576862'
down_revision = '40f58b15ecd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasources', 'ref_auth_type',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('datasources', 'ref_auth_type',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
