"""empty message

Revision ID: a73e7f9f4358
Revises: 01afc23494aa
Create Date: 2022-02-08 13:05:36.528276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a73e7f9f4358'
down_revision = '01afc23494aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasources', sa.Column('httpaddress', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('apibaseurl', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('apischemeurl', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('authorizationjson', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('autorizationlogin', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('autorizationpassword', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('autorizationtoken', sa.String(length=150), nullable=True))
    op.add_column('datasources', sa.Column('marked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datasources', 'marked')
    op.drop_column('datasources', 'autorizationtoken')
    op.drop_column('datasources', 'autorizationpassword')
    op.drop_column('datasources', 'autorizationlogin')
    op.drop_column('datasources', 'authorizationjson')
    op.drop_column('datasources', 'apischemeurl')
    op.drop_column('datasources', 'apibaseurl')
    op.drop_column('datasources', 'httpaddress')
    # ### end Alembic commands ###
