"""empty message

Revision ID: aefd118553e5
Revises: afed7bca7d50
Create Date: 2022-02-07 14:38:51.820936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aefd118553e5'
down_revision = 'afed7bca7d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'auth_type', ['guid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_type', type_='unique')
    # ### end Alembic commands ###
