"""empty message

Revision ID: afed7bca7d50
Revises: 
Create Date: 2022-02-07 14:21:14.695545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'afed7bca7d50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_type',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('enumname', sa.String(length=100), nullable=True),
    sa.Column('enumorder', sa.Numeric(precision=10), nullable=False),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_type')
    # ### end Alembic commands ###
