"""empty message

Revision ID: d164dcdd5e18
Revises: aefd118553e5
Create Date: 2022-02-08 12:32:43.397145

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd164dcdd5e18'
down_revision = 'aefd118553e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasources',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.PrimaryKeyConstraint('guid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('datasources')
    # ### end Alembic commands ###
